# Site settings
title: Software Engineering Practicum Organization
tagline: A collection of student created software projects
author_name: Dr Cengiz Gunay
author_link: http://www.ggc.edu/about-ggc/directory/cengiz-gunay
email: cengique@users.sf.net
description: > # this means to ignore newlines until "baseurl:"
        This is an educational organization to host software development/engineering projects.
baseurl: "" # baseurl is the subpath of your site, e.g. blog/ - not including initial /
url: "https://soft-eng-practicum.github.io/" # the base hostname & protocol for your site
twitter_username: cengique
github_username:  cengique
repository: soft-eng-practicum/soft-eng-practicum.github.io
profs:
  gunay:
    name: "Dr. Cengiz Gunay"
    url: https://www.ggc.edu/about-ggc/directory/cengiz-gunay
  doloc-mihu:
    name: "Dr. Anca Doloc-Mihu"
    url: https://www.ggc.edu/about-ggc/directory/anca-doloc-mihu
collections:
  itec3870_sp23:
    title: "Spring 2023 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Spring 2023"
    course: "SD2"
    date: 2023-04-28
    output: true
  itec3870_fa22:
    title: "Fall 2022 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Fall 2022"
    course: "SD2"
    date: 2022-11-25
    output: true
  itec3870_fa21:
    title: "Fall 2021 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Fall 2021"
    course: "SD2"
    date: 2021-11-18
    output: true
  itec3870_fa20:
    title: "Fall 2020 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Fall 2020"
    course: "SD2"
    date: 2020-11-23
    output: true
  itec3870_sp20:
    title: "Spring 2020 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Spring 2020"
    course: "SD2"
    date: 2020-04-20
    output: true
  itec3870_fa19:
    title: "Fall 2019 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Fall 2019"
    course: "SD2"
    date: 2019-12-14
    output: true
  itec3870_sp19:
    title: "Spring 2019 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Spring 2019"
    course: "SD2"
    date: 2019-05-04
    output: true
  itec3870_fa18:
    title: "Fall 2018 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Fall 2018"
    course: "SD2"
    date: 2018-11-26
    output: true
  itec3870_sp18:
    title: "Spring 2018 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Spring 2018"
    course: "SD2"
    date: 2018-05-17
    output: true
  itec3870_fa17:
    title: "Fall 2017 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Fall 2017"
    course: "SD2"
    date: 2017-11-30
    output: true
  itec3870_sp17:
    title: "Spring 2017 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Spring 2017"
    course: "SD2"
    date: 2017-05-10
    output: true
  itec3870_fa16:
    title: "Fall 2016 ITEC 3870 Soft Dev 2 course projects"
    menutitle:  "Fall 2016"
    course: "SD2"
    date: 2016-12-01
    output: true

# Build settings
markdown: kramdown
plugins:
  - jemoji
sass:
  style: compressed # saves 25% space
