# Site settings
title: Software Engineering Practicum Organization
tagline: A collection of student-created software projects
author_name: Dr Cengiz Gunay
author_link: http://www.ggc.edu/about-ggc/directory/cengiz-gunay
email: cengique@users.sf.net
description: > # this means to ignore newlines until "baseurl:"
        This is an educational organization to host software development/engineering projects.
baseurl: "" # baseurl is the subpath of your site, e.g. blog/ - not including initial /
url: "https://soft-eng-practicum.github.io/" # the base hostname & protocol for your site
twitter_username: cengique
github_username:  cengique
repository: soft-eng-practicum/soft-eng-practicum.github.io
profs:
  gunay:
    name: "Dr. Cengiz Gunay"
    url: https://www.ggc.edu/about-ggc/directory/cengiz-gunay
  doloc-mihu:
    name: "Dr. Anca Doloc-Mihu"
    url: https://www.ggc.edu/about-ggc/directory/anca-doloc-mihu
collections:
  projects:
    title: "Projects"
    menutitle: "Projects"
    date: 2025-01-01
    output: true
  partners:
    title: "Partners"
    menutitle: "Partners"
    date: 2025-01-01
    output: true
  students:
    title: "Students"
    menutitle: "Students"
    date: 2025-01-01
    output: true

#exclude: [ "README.md", "**/README.md", "**/*.template.md" ]
exclude:
  - vendor/
  - .bundle/
  - .devcontainer/
  - .git/
  - .github/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - Containerfile
  - Dockerfile
  - README.md
  - "**/README.md"
  - "**/*.template.md"

# Build settings
markdown: kramdown
plugins:
  - jemoji
sass:
  style: compressed # saves 25% space
